development:
    adapter: postgresql
    encoding: unicode
    database: sample_db_dev
    username: mk
    pool: 5

test:
    adapter: postgresql
    encoding: unicode
    database: sample_db_test
    username: mk
    pool: 5